[global]

uuid = "E7911DAD-15AC-44F4-A95D-74AB940A19FB"
extension = ".png"
publish_date = 2023-07-01T00:00:00+09:00

[user_defined]

# 自由に使える欄

# 以下、旧仕様

[introduction]

uuid = "E7911DAD-15AC-44F4-A95D-74AB940A19FB"
extension = ".png"
title = "マップ用タイルセット様式８ｘ１９"
author = "Muzudho"
publish_date = 2023-07-01

[comment]

# 自由に使える欄
