namespace _2D_RPG_Negiramen.Models;

/// <summary>
///     😁 プロジェクト・ヘルパー
/// </summary>
internal class ProjectHelper
{
    // - インターナル静的メソッド

    #region メソッド（構成、設定は有効か？）
    /// <summary>
    ///     構成、設定は有効か？
    /// </summary>
    /// <returns>そうだ</returns>
    internal static bool IsReady()
    {
        // スターターキットのディレクトリーが存在する
        return App.GetOrLoadProjectConfiguration().StarterKitFolder.IsDirectoryExists() &&
            // Unity の Auto Generated フォルダーが存在する
            App.GetOrLoadProjectConfiguration().UnityAssetsFolder.YourCircleFolder.YourWorkFolder.AutoGeneratedFolder.IsDirectoryExists();
    }
    #endregion
}
