namespace _2D_RPG_Negiramen.Models
{
    /// <summary>
    ///     Unity の Assets フォルダーを想定したもの
    /// </summary>
    internal class UnityAssetsFolder
    {
        /// <summary>
        ///     Unity の Assets フォルダーにファイルを送り込みます
        ///     
        ///     <pre>
        ///         👉　└─ 📂 Assets
        ///     </pre>
        /// </summary>
        /// <param name="unityAssetsFolderPath">Unityのアセット・フォルダーへのパス</param>
        /// <returns>完了した</returns>
        internal static bool PushStartupMemberToUnityAssetsFolder(string unityAssetsFolderPath)
        {

            if (!Directory.Exists(unityAssetsFolderPath))
            {
                // TODO Unity の Assets フォルダ―へのパスでなければ失敗
                return false;
            }

            var yourCircleNameFolderPath = Path.Combine(unityAssetsFolderPath, App.GetOrLoadConfiguration().YourCircleName.AsStr);

            if (!Directory.Exists(yourCircleNameFolderPath))
            {
                // 無ければ作成
                Directory.CreateDirectory(yourCircleNameFolderPath);
            }

            UnityAssetsFolder.PushStartupMemberToYourCircleNameFolder(yourCircleNameFolderPath);

            return true;
        }

        /// <summary>
        ///     Unity の Assets フォルダーにファイルを送り込みます
        ///     
        ///     <pre>
        ///         　　└─ 📂 Assets
        ///         👉　　　└─ 📂 {Your Circle Name}
        ///     </pre>
        /// </summary>
        /// <param name="yourCircleNameFolderPath">あなたのサークル名フォルダ―へのパス</param>
        static void PushStartupMemberToYourCircleNameFolder(string yourCircleNameFolderPath)
        {
            var yourWorkNameFolderPath = Path.Combine(yourCircleNameFolderPath, App.GetOrLoadConfiguration().YourWorkName.AsStr);

            if (!Directory.Exists(yourWorkNameFolderPath))
            {
                // 無ければ作成
                Directory.CreateDirectory(yourWorkNameFolderPath);
            }

            UnityAssetsFolder.PushStartupMemberToYourWorkNameFolder(yourWorkNameFolderPath);
        }

        /// <summary>
        ///     Unity の Assets フォルダーにファイルを送り込みます
        ///     
        ///     <pre>
        ///         　　└─ 📂 Assets
        ///         　　　　└─ 📂 {Your Circle Name}
        ///         👉　　　　　└─ 📂 {Your Work Name}
        ///     </pre>
        /// </summary>
        /// <param name="yourWorkNameFolderPath">あなたの作品名フォルダ―へのパス</param>
        static void PushStartupMemberToYourWorkNameFolder(string yourWorkNameFolderPath)
        {
            var autoGeneratedFolderPath = Path.Combine(yourWorkNameFolderPath, "Auto Generated");

            if (!Directory.Exists(autoGeneratedFolderPath))
            {
                // 無ければ作成
                Directory.CreateDirectory(autoGeneratedFolderPath);
            }

            UnityAssetsFolder.PushStartupMemberToAutoGeneratedFolder(autoGeneratedFolderPath);
        }

        /// <summary>
        ///     Unity の Assets フォルダーにファイルを送り込みます
        ///     
        ///     <pre>
        ///         　　└─ 📂 Assets
        ///         　　　　└─ 📂 {Your Circle Name}
        ///         　　　　　　└─ 📂 {Your Work Name}
        ///         👉　　　　　　　└─ 📂 {Auto Generated}
        ///     </pre>
        /// </summary>
        /// <param name="autoGeneratedFolderPath">自動生成フォルダ―へのパス</param>
        static void PushStartupMemberToAutoGeneratedFolder(string autoGeneratedFolderPath)
        {
            // データ・フォルダー
            var dataFolderPath = Path.Combine(autoGeneratedFolderPath, "Data");
            if (!Directory.Exists(dataFolderPath))
            {
                Directory.CreateDirectory(dataFolderPath);
            }
            UnityAssetsFolder.PushStartupMemberToDataFolder(dataFolderPath);

            // エディター・フォルダー
            var editorFolderPath = Path.Combine(autoGeneratedFolderPath, "Editor");
            if (!Directory.Exists(editorFolderPath))
            {
                Directory.CreateDirectory(editorFolderPath);
            }

            // 画像フォルダー
            var imagesFolderPath = Path.Combine(autoGeneratedFolderPath, "Images");
            if (!Directory.Exists(imagesFolderPath))
            {
                Directory.CreateDirectory(imagesFolderPath);
            }

            // 材質フォルダー
            var materialsFolderPath = Path.Combine(autoGeneratedFolderPath, "Materials");
            if (!Directory.Exists(materialsFolderPath))
            {
                Directory.CreateDirectory(materialsFolderPath);
            }

            // 映像フォルダー
            var moviesFolderPath = Path.Combine(autoGeneratedFolderPath, "Movies");
            if (!Directory.Exists(moviesFolderPath))
            {
                Directory.CreateDirectory(moviesFolderPath);
            }

            // プレファブ・フォルダー
            var prefabFolderPath = Path.Combine(autoGeneratedFolderPath, "Prefabs");
            if (!Directory.Exists(prefabFolderPath))
            {
                Directory.CreateDirectory(prefabFolderPath);
            }

            // シーン・フォルダー
            var scenesFolderPath = Path.Combine(autoGeneratedFolderPath, "Scenes");
            if (!Directory.Exists(scenesFolderPath))
            {
                Directory.CreateDirectory(scenesFolderPath);
            }

            // スクリプト・フォルダー
            var scriptsFolderPath = Path.Combine(autoGeneratedFolderPath, "Scripts");
            if (!Directory.Exists(scriptsFolderPath))
            {
                Directory.CreateDirectory(scriptsFolderPath);
            }

            // スクリプティング・オブジェクト・フォルダー
            var scriptingObjectsFolderPath = Path.Combine(autoGeneratedFolderPath, "Scripting Objects");
            if (!Directory.Exists(scriptingObjectsFolderPath))
            {
                Directory.CreateDirectory(scriptingObjectsFolderPath);
            }

            // 音フォルダー
            var soundsFolderPath = Path.Combine(autoGeneratedFolderPath, "Sounds");
            if (!Directory.Exists(soundsFolderPath))
            {
                Directory.CreateDirectory(soundsFolderPath);
            }

            // システム・フォルダー
            var systemFolderPath = Path.Combine(autoGeneratedFolderPath, "System");
            if (!Directory.Exists(systemFolderPath))
            {
                Directory.CreateDirectory(systemFolderPath);
            }

            // テキスト・フォルダー
            var textsFolderPath = Path.Combine(autoGeneratedFolderPath, "Texts");
            if (!Directory.Exists(textsFolderPath))
            {
                Directory.CreateDirectory(textsFolderPath);
            }
        }

        /// <summary>
        ///     Unity の Assets フォルダーにファイルを送り込みます
        ///     
        ///     <pre>
        ///         　　└─ 📂 Assets
        ///         　　　　└─ 📂 {Your Circle Name}
        ///         　　　　　　└─ 📂 {Your Work Name}
        ///         　　　　　　　　└─ 📂 {Auto Generated}
        ///         👉　　　　　　　　　└─ 📂 Data
        ///     </pre>
        /// </summary>
        /// <param name="dataFolderPath">データ・フォルダ―へのパス</param>
        static void PushStartupMemberToDataFolder(string dataFolderPath)
        {
            // JSON形式ファイル・フォルダー
            var jsonFolderPath = Path.Combine(dataFolderPath, "JSON");
            if (!Directory.Exists(jsonFolderPath))
            {
                Directory.CreateDirectory(jsonFolderPath);
            }
        }
    }
}
