//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2D_RPG_Negiramen.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_2D_RPG_Negiramen.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   構成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戦闘画面を作る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateABattleScreen {
            get {
                return ResourceManager.GetString("CreateABattleScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会話画面を作る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateAConversationScreen {
            get {
                return ResourceManager.GetString("CreateAConversationScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マップ画面を作る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateAMapScreen {
            get {
                return ResourceManager.GetString("CreateAMapScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メニュー画面を作る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateAMenuScreen {
            get {
                return ResourceManager.GetString("CreateAMenuScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   モンスター・グループを編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditAMonsterGroup {
            get {
                return ResourceManager.GetString("EditAMonsterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイテムを編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレイヤー・キャラクターを編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditPlayerCharacter {
            get {
                return ResourceManager.GetString("EditPlayerCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   モンスターを編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditTheMonster {
            get {
                return ResourceManager.GetString("EditTheMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   話しを編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditTheTalk {
            get {
                return ResourceManager.GetString("EditTheTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データを編集する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditYourData {
            get {
                return ResourceManager.GetString("EditYourData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画面をレイアウトする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutTheScreen {
            get {
                return ResourceManager.GetString("LayoutTheScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マップ描画ページ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MapDrawingPage {
            get {
                return ResourceManager.GetString("MapDrawingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポップアップ練習 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupExercises {
            get {
                return ResourceManager.GetString("PopupExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語を選ぶ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイル・パレット表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TilePaletteDisplay {
            get {
                return ResourceManager.GetString("TilePaletteDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイル・パレット編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TilePaletteEditing {
            get {
                return ResourceManager.GetString("TilePaletteEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ表示テスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowDisplayTest {
            get {
                return ResourceManager.GetString("WindowDisplayTest", resourceCulture);
            }
        }
    }
}
