//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2D_RPG_Negiramen.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_2D_RPG_Negiramen.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ２D　ＲＰＧ　ネギラーメン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _2dRpgNegiramen {
            get {
                return ResourceManager.GetString("_2dRpgNegiramen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャッシュ・ディレクトリー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CacheDirectory {
            get {
                return ResourceManager.GetString("CacheDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このフォルダの下は自動編集されます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigurationPageAutoGeneratedFolderDescription {
            get {
                return ResourceManager.GetString("ConfigurationPageAutoGeneratedFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unity の Assets フォルダへ足りてないファイルを転送 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigurationPageDeployButtonDescription {
            get {
                return ResourceManager.GetString("ConfigurationPageDeployButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたがローカルＰＣへダウンロードした 2D RPG Negiramen に含まれる Starter Kit フォルダへのパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigurationPageStarterKitFolderDescription {
            get {
                return ResourceManager.GetString("ConfigurationPageStarterKitFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unity プロジェクトの中の Assets フォルダへのパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigurationPageUnityAssetsFolderDescription {
            get {
                return ResourceManager.GetString("ConfigurationPageUnityAssetsFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unity プロジェクトを 2D テンプレートで作成してから、以下を設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigurationPageUnityProjectDescription {
            get {
                return ResourceManager.GetString("ConfigurationPageUnityProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   構成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlCode {
            get {
                return ResourceManager.GetString("ControlCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戦闘画面を作る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateABattleScreen {
            get {
                return ResourceManager.GetString("CreateABattleScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会話画面を作る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateAConversationScreen {
            get {
                return ResourceManager.GetString("CreateAConversationScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マップ画面を作る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateAMapScreen {
            get {
                return ResourceManager.GetString("CreateAMapScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メニュー画面を作る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateAMenuScreen {
            get {
                return ResourceManager.GetString("CreateAMenuScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カーソル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cursor {
            get {
                return ResourceManager.GetString("Cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   モンスター・グループを編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditAMonsterGroup {
            get {
                return ResourceManager.GetString("EditAMonsterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイテムを編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プレイヤー・キャラクターを編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditPlayerCharacter {
            get {
                return ResourceManager.GetString("EditPlayerCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   モンスターを編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditTheMonster {
            get {
                return ResourceManager.GetString("EditTheMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   話しを編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditTheTalk {
            get {
                return ResourceManager.GetString("EditTheTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データを編集する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditYourData {
            get {
                return ResourceManager.GetString("EditYourData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グリッド１ます に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GridOne {
            get {
                return ResourceManager.GetString("GridOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グリッド位相 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GridPhase {
            get {
                return ResourceManager.GetString("GridPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   たて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コードのおぼえかた に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HowToRememberControlCode {
            get {
                return ResourceManager.GetString("HowToRememberControlCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   交差中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Intersecting {
            get {
                return ResourceManager.GetString("Intersecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画面をレイアウトする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutTheScreen {
            get {
                return ResourceManager.GetString("LayoutTheScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ひだり に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン（１） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoginPage1 {
            get {
                return ResourceManager.GetString("LoginPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン（２） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoginPage2 {
            get {
                return ResourceManager.GetString("LoginPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マップ描画ページ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MapDrawingPage {
            get {
                return ResourceManager.GetString("MapDrawingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポップアップ練習 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PopupExercises {
            get {
                return ResourceManager.GetString("PopupExercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語を選ぶ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイル切抜き に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TileCrop {
            get {
                return ResourceManager.GetString("TileCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイル・パレット表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TilePaletteDisplay {
            get {
                return ResourceManager.GetString("TilePaletteDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイルセット一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TilesetList {
            get {
                return ResourceManager.GetString("TilesetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイル タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TileTitle {
            get {
                return ResourceManager.GetString("TileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   うえ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   よこ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ表示テスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowDisplayTest {
            get {
                return ResourceManager.GetString("WindowDisplayTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたのサークル名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YourCircleName {
            get {
                return ResourceManager.GetString("YourCircleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あなたの作品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YourWorkName {
            get {
                return ResourceManager.GetString("YourWorkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ズーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
