namespace _2D_RPG_Negiramen.Models.FileEntries
{
    using _2D_RPG_Negiramen.Models.FileEntries.Locations.UnityAssets;
    using TheLocationOfUnityAssets = _2D_RPG_Negiramen.Models.FileEntries.Locations.UnityAssets;

    /// <summary>
    ///     😁 Unity の Assets フォルダを想定したもの
    /// </summary>
    internal class UnityAssetsDeployment
    {
        // - インターナル静的メソッド

        #region メソッド（Unity の Assets フォルダにファイルを送り込みます）
        /// <summary>
        ///     <pre>
        ///         Unity の 📂 `Assets` フォルダにファイルを送り込みます
        ///     
        ///             📂 例: C:/Users/むずでょ/Documents/Unity Projects/Negiramen Practice/
        ///         👉　└─ 📂 Assets
        ///     </pre>
        /// </summary>
        /// <param name="unityAssetsFolder">Unityの 📂 `Assets` フォルダの場所</param>
        /// <returns>完了した</returns>
        internal static bool PushStartupMemberToUnityAssetsFolder(TheLocationOfUnityAssets.ItsFolder unityAssetsFolder)
        {
            if (!Directory.Exists(unityAssetsFolder.Path.AsStr))
            {
                // TODO Unity の Assets フォルダ―へのパスでなければ失敗
                return false;
            }

            if (!Directory.Exists(unityAssetsFolder.YourCircleNameFolder.Path.AsStr))
            {
                // 無ければ作成
                Directory.CreateDirectory(unityAssetsFolder.YourCircleNameFolder.Path.AsStr);
            }

            PushStartupMemberToYourCircleNameFolder(unityAssetsFolder.YourCircleNameFolder);

            return true;
        }
        #endregion

        /// <summary>
        ///     <pre>
        ///          Unity の 📂 `Assets/｛あなたのサークル名｝` フォルダにファイルを送り込みます
        ///     
        ///             📂 例: C:/Users/むずでょ/Documents/Unity Projects/Negiramen Practice/
        ///         　　└─ 📂 Assets
        ///         👉　　　└─ 📂 {Your Circle Name}
        ///     </pre>
        /// </summary>
        /// <param name="yourCircleNameFolderPath">あなたのサークル名フォルダ―へのパス</param>
        static void PushStartupMemberToYourCircleNameFolder(TheLocationOfUnityAssets.YourCircleNameFolder yourCircleNameFolder)
        {
            if (!Directory.Exists(yourCircleNameFolder.YourWorkNameFolder.Path.AsStr))
            {
                // 無ければ作成
                Directory.CreateDirectory(yourCircleNameFolder.YourWorkNameFolder.Path.AsStr);
            }

            PushStartupMemberToYourWorkNameFolder(yourCircleNameFolder.YourWorkNameFolder);
        }

        /// <summary>
        ///     <pre>
        ///         Unity の 📂 `Assets/｛あなたのサークル名｝/｛あなたの作品名｝` フォルダにファイルを送り込みます
        ///     
        ///             📂 例: C:/Users/むずでょ/Documents/Unity Projects/Negiramen Practice/
        ///         　　└─ 📂 Assets
        ///         　　　　└─ 📂 {Your Circle Name}
        ///         👉　　　　　└─ 📂 {Your Work Name}
        ///     </pre>
        /// </summary>
        /// <param name="yourWorkNameFolderPath">あなたの作品名フォルダ―へのパス</param>
        static void PushStartupMemberToYourWorkNameFolder(TheLocationOfUnityAssets.YourWorkNameFolder yourWorkNameFolder)
        {
            if (!Directory.Exists(yourWorkNameFolder.AutoGeneratedFolder.Path.AsStr))
            {
                // 無ければ作成
                Directory.CreateDirectory(yourWorkNameFolder.AutoGeneratedFolder.Path.AsStr);
            }

            PushStartupMemberToAutoGeneratedFolder(yourWorkNameFolder.AutoGeneratedFolder);
        }

        // - ４階層目

        /// <summary>
        ///     <pre>
        ///         Unity の 📂 `Assets/｛あなたのサークル名｝/｛あなたの作品名｝/Auto Generated` フォルダにファイルを送り込みます
        ///     
        ///             📂 例: C:/Users/むずでょ/Documents/Unity Projects/Negiramen Practice/
        ///         　　└─ 📂 Assets
        ///         　　　　└─ 📂 {Your Circle Name}
        ///         　　　　　　└─ 📂 {Your Work Name}
        ///         👉　　　　　　　└─ 📂 {Auto Generated}
        ///     </pre>
        /// </summary>
        /// <param name="autoGeneratedFolderPath">自動生成フォルダ―へのパス</param>
        static void PushStartupMemberToAutoGeneratedFolder(TheLocationOfUnityAssets.AutoGeneratedFolder autoGeneratedFolder)
        {
            // データ・フォルダ
            autoGeneratedFolder.DataFolder.CreateThisDirectoryIfItDoesNotExist();
            PushStartupMemberToDataFolder(autoGeneratedFolder.DataFolder);

            // エディター・フォルダ
            autoGeneratedFolder.EditorFolder.CreateThisDirectoryIfItDoesNotExist();

            // 画像フォルダ
            autoGeneratedFolder.ImagesFolder.CreateThisDirectoryIfItDoesNotExist();
            PushStartupMemberToImagesFolder(autoGeneratedFolder.ImagesFolder);

            // 材質フォルダ
            autoGeneratedFolder.MaterialsFolder.CreateThisDirectoryIfItDoesNotExist();

            // 映像フォルダ
            autoGeneratedFolder.MoviesFolder.CreateThisDirectoryIfItDoesNotExist();

            // プレファブ・フォルダ
            autoGeneratedFolder.PrefabsFolder.CreateThisDirectoryIfItDoesNotExist();

            // シーン・フォルダ
            autoGeneratedFolder.ScenesFolder.CreateThisDirectoryIfItDoesNotExist();

            // スクリプト・フォルダ
            autoGeneratedFolder.ScriptsFolder.CreateThisDirectoryIfItDoesNotExist();

            // スクリプティング・オブジェクト・フォルダ
            autoGeneratedFolder.ScriptingObjectsFolder.CreateThisDirectoryIfItDoesNotExist();

            // 音フォルダ
            autoGeneratedFolder.SoundsFolder.CreateThisDirectoryIfItDoesNotExist();

            // システム・フォルダ
            var systemFolderPath = Path.Combine(autoGeneratedFolder.Path.AsStr, "System");
            if (!Directory.Exists(systemFolderPath))
            {
                Directory.CreateDirectory(systemFolderPath);
            }

            // テキスト・フォルダ
            var textsFolderPath = Path.Combine(autoGeneratedFolder.Path.AsStr, "Texts");
            if (!Directory.Exists(textsFolderPath))
            {
                Directory.CreateDirectory(textsFolderPath);
            }
        }

        // - ５階層目

        /// <summary>
        ///     <pre>
        ///         Unity の 📂 `Assets/｛あなたのサークル名｝/｛あなたの作品名｝/Auto Generated/Images` フォルダにファイルを送り込みます
        ///     
        ///             📂 例: C:/Users/むずでょ/Documents/Unity Projects/Negiramen Practice/
        ///         　　└─ 📂 Assets
        ///         　　　　└─ 📂 {Your Circle Name}
        ///         　　　　　　└─ 📂 {Your Work Name}
        ///         　　　　　　　　└─ 📂 {Auto Generated}
        ///         👉　　　　　　　　　└─ 📂 Images
        ///     </pre>
        /// </summary>
        /// <param name="imagesFolder">画像フォルダ―の場所</param>
        static void PushStartupMemberToImagesFolder(TheLocationOfUnityAssets.ImagesFolder imagesFolder)
        {
            // 📂 `Tileset` フォルダ
            if (!Directory.Exists(imagesFolder.TilesetsFolder.Path.AsStr))
            {
                Directory.CreateDirectory(imagesFolder.TilesetsFolder.Path.AsStr);
            }

            CopyTileset(imagesFolder.TilesetsFolder, "adventure_field.png");
            CopyTileset(imagesFolder.TilesetsFolder, "map-tileset-format-8x19.png");

            //var configuration = App.GetOrLoadConfiguration();
            //var source = Path.Combine(configuration.NegiramenWorkspaceFolderPath.AsStr, "Assets", "Images", "Tilesets", "adventure_field.png");
            //var destination = Path.Combine(
            //        configuration.UnityAssetsFolderPath.AsStr,
            //        configuration.YourCircleName.AsStr,
            //        configuration.YourWorkName.AsStr,
            //        "Auto Generated",
            //        "Images",
            //        "Tilesets",
            //        "adventure_field.png");

            //if (!File.Exists(destination))
            //{
            //    // 📄 `Tileset` ファイルを複写
            //    File.Copy(
            //        sourceFileName: source,
            //        destFileName: destination);
            //}
        }

        /// <summary>
        ///     タイルセットをコピー
        /// </summary>
        /// <param name="fileName">ファイル名</param>
        static void CopyTileset(TheLocationOfUnityAssets.ImagesTilesetsFolder tilesetFolder, string fileName)
        {
            var configuration = App.GetOrLoadConfiguration();

            // 画像ファイルのコピー
            {
                var source = Path.Combine(configuration.NegiramenWorkspaceFolder.Path.AsStr, "For Unity Assets", "Images", "Tilesets", fileName);
                var destination = Path.Combine(tilesetFolder.Path.AsStr, fileName);

                if (!File.Exists(destination))
                {
                    // ファイルを複写
                    File.Copy(
                        sourceFileName: source,
                        destFileName: destination);
                }
            }

            // 添付の TOML ファイルのコピー
            {
                var fileStem = Path.GetFileNameWithoutExtension(fileName);
                var source = Path.Combine(configuration.NegiramenWorkspaceFolder.Path.AsStr, "For Unity Assets", "Images", "Tilesets", $"{fileStem}.toml");
                var destination = Path.Combine(tilesetFolder.Path.AsStr, $"{fileStem}.toml");

                if (!File.Exists(destination))
                {
                    // ファイルを複写
                    File.Copy(
                        sourceFileName: source,
                        destFileName: destination);
                }
            }
        }

        /// <summary>
        ///     <pre>
        ///         Data フォルダにファイルを送り込みます
        ///     
        ///             📂 例: C:/Users/むずでょ/Documents/Unity Projects/Negiramen Practice/
        ///         　　└─ 📂 Assets
        ///         　　　　└─ 📂 {Your Circle Name}
        ///         　　　　　　└─ 📂 {Your Work Name}
        ///         　　　　　　　　└─ 📂 {Auto Generated}
        ///         👉　　　　　　　　　└─ 📂 Data
        ///     </pre>
        /// </summary>
        /// <param name="dataFolderPath">データ・フォルダ―へのパス</param>
        static void PushStartupMemberToDataFolder(TheLocationOfUnityAssets.DataFolder dataFolder)
        {
            // CSVN形式ファイル・フォルダへのパス
            var csv = Path.Combine(dataFolder.Path.AsStr, "CSV");
            if (!Directory.Exists(csv))
            {
                Directory.CreateDirectory(csv);
            }
            PushStartupMemberToDataCSVFolder(csv);

            // JSON形式ファイル・フォルダへのパス
            var json = Path.Combine(dataFolder.Path.AsStr, "JSON");
            if (!Directory.Exists(json))
            {
                Directory.CreateDirectory(json);
            }
        }

        // - ６階層目

        /// <summary>
        ///     <pre>
        ///         CSV フォルダのメンバーを準備します
        ///     
        ///             📂 例: C:/Users/むずでょ/Documents/Unity Projects/Negiramen Practice/
        ///         　　└─ 📂 Assets
        ///         　　　　└─ 📂 {Your Circle Name}
        ///         　　　　　　└─ 📂 {Your Work Name}
        ///         　　　　　　　　└─ 📂 {Auto Generated}
        ///         　　　　　　　　　　└─ 📂 Data
        ///         👉　　　　　　　　　　　└─ 📂 CSV
        ///     </pre>
        /// </summary>
        /// <param name="csvFolderPath">ＣＳＶフォルダ―へのパス</param>
        static void PushStartupMemberToDataCSVFolder(string csvFolderPath)
        {
            // タイルセット
            var tilesets = Path.Combine(csvFolderPath, "Tilesets");
            if (!Directory.Exists(tilesets))
            {
                Directory.CreateDirectory(tilesets);
            }
        }
    }
}
